Coursera/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import  handler404, handler403, handler500

handler404 = 'courses.views.view_404'
handler500 = 'courses.views.view_500'
handler403 = 'courses.views.view_403'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('courses.urls',namespace='courses')),
    path('', include('blog.urls',namespace='blogs')),
    path('', include('users.urls',namespace='users')),
    path('accounts/', include('allauth.urls')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import PostListView,PostDetailView, create_post, delete_post

app_name = 'blogs'

urlpatterns = [

    path("blog/",PostListView.as_view(),name='post_list'),
    path('blog/<int:pk>/',PostDetailView.as_view(),name='post_detail'),
    path('blog/create/', create_post, name='create_post'),
    path('blog/<int:id>/delete', delete_post, name='delete_post'),


]

courses/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from courses.views import HomeView,AboutView,ContactView,CourseListView, CourseDetailView,LessonDetailView, SearchView, krijo_klase, krijo_lende, krijo_mesim

app_name = 'courses'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('courses/<int:category>', CourseListView, name='course_list'),
    path('courses/<slug>/', login_required(CourseDetailView.as_view()), name='course_detail'),
    path('courses/<course_slug>/<lesson_slug>/', login_required(LessonDetailView.as_view()), name='lesson_detail'),
    path('search/', SearchView, name='kerko_kurs'),
    path('krijo/klase', krijo_klase, name='krijo_klase'),
    path('krijo/lende', krijo_lende, name='krijo_lende'),
    path('krijo/mesim', krijo_mesim, name='krijo_mesim')
]

users/urls.py
from django.urls import path

from users.views import Profile, kerkesa

app_name = 'users'

urlpatterns = [
    path('profile/', Profile, name='profile'),
    path('kerkesa/', kerkesa, name='kerkesa')

]

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="/">Entête</a>
      <span>About</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<section class="about-us py-5 " id="about-us">
    <div class="container mt-5">
	<div class="row">
		<div class="col-md-6">
		    <h1 class='text-primary'>Accueillir!</h1>
		    <h2>En savoir plus sur nous</h2>
		    <hr>
		    <p></p>
		    <p></p>
		    <button type="button" class="btn btn-primary">Let's Know More</button>

		</div>
		<div class="col-md-6">
		    <img src="http://themebubble.com/demo/marketingpro/wp-content/uploads/2016/10/seo-slide.png "alt="">
		</div>
	</div>
</div>
</section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<title>E-ducate Online </title>
	<meta charset="UTF-8">
	<meta name="description" content="WebUni Education Template">
	<meta name="keywords" content="webuni, education, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->
	<link href="{% static 'webuni/img/favicon.png' %}" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Raleway:400,400i,500,500i,600,600i,700,700i,800,800i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'webuni/css/bootstrap.min.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/style.css'%}"/>
	<link rel="stylesheet" href="{% static 'webuni/css/freelancer.css'%}"/>
	<link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />


	

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<nav class="navbar navbar-expand-lg bg-white text-uppercase" id="mainNav">
		<div class="container">
			<a class="navbar-brand js-scroll-trigger" href="/">
				<img src="{% static 'webuni/img/logonew3.png' %}" alt="" width="150" height="50">
			  </a>
			  
		  <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
			Menu
	
		  </button>
		  <div class="collapse navbar-collapse" id="navbarResponsive">
			<ul class="navbar-nav ml-auto">
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:home' %}" style="color: black;">Home</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<li class="nav-item mx-0 mx-lg-1">
					<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="/#kurset" style="color: black;">Cours</a>
				  </li>
			  </li> 
			  {% if request.user.profile.is_teacher == True %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:krijo_klase' %}" style="color: black;">Créer des cours</a>
			  </li>
			  
			  
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:contact' %}" style="color: black;">Contact</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'courses:about' %}" style="color: black;">About</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'blogs:post_list' %}" style="color: black;">Blog</a>
			  </li>
			  {% endif %}
			  {% if request.user.is_authenticated %}
			  
			  <div class="dropdown show">
				<a class=" dropdown-toggle nav-link py-3 px-0 px-lg-3 rounded js-scroll-triggeraa" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					{{request.user.username}}
				</a>
			  
				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
				  <a class="dropdown-item" href="{% url 'users:profile' %}">Profil</a>
				  <a class="dropdown-item" href="{% url 'account_logout' %}">Déconnexion</a>
				</div>
			  </div>
			  {% else %}
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_login' %}">Login</a>
			  </li>
			  <li class="nav-item mx-0 mx-lg-1">
				<a class="active nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="{% url 'account_signup' %}">S'inscrire</a>
			  </li>
              {% endif %}
			</ul>
		  </div>
		</div>
	  </nav>

{% include 'inc/messages.html' %}
{% block content %}

{% endblock content %}

{% if request.user.is_authenticated %}
{% else %}
	<!-- banner section -->
	<section class="banner-section spad">
		<div class="container">
			<div class="section-title mb-0 pb-2">
				<h2>Rejoignez notre communauté!</h2>
				<p>Leçons scolaires gratuites à travers des vidéos et des communications avec les enseignants et les autres membres de E-ducate. C'est très simple, la seule chose que vous devez faire est de vous inscrire. Cliquez ci-dessous : </p>
			</div>
			<div class="text-center pt-5">
				<a href="{% url 'account_signup' %}" class="site-btn">S'inscrire maintenant!</a>
			</div>
		</div>
	</section>
	<!-- banner section end -->
{% endif %}


	<!-- footer section -->
	<footer class="footer-section spad pb-0">
		<div class="footer-top">
			<div class="footer-warp">
				<div class="row">
					<div class="widget-item">
						<h4>Coordonnées</h4>
						<ul class="contact-list">
							<li>Maroc </li>
							<li>+212 6 00-75-13-74</li>
							<li>ounairzineb@gmail.com</li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Classe</h4>
						<ul>
							<li><a href="">Mathématique</a></li>
							<li><a href="">Littérature et langue</a></li>
							<li><a href="">chimie</a></li>
							<li><a href="">Biologie</a></li>
							<li><a href="">Programmation</a></li>
						</ul>
					</div>
					<div class="widget-item">
						<h4>Personnel</h4>
						<ul>
							<li><a href="">Enseignants</a></li>
							<li><a href="">Prix</a></li>
							<li><a href="">Les meilleurs élèves</a></li>
							<li><a href="">Blogs</a></li>
							
						</ul>
					</div>
					<div class="widget-item">
						<h4>Réseaux sociaux</h4>
						<ul>
							<li><a href="">YouTube</a></li>
							<li><a href="">Facebook</a></li>
							<li><a href="">Instagram</a></li>
							<li><a href="">Twitter</a></li>
							<li><a href="">Linked In</a></li>
					
						</ul>
					</div>
					<div class="widget-item">
						<h4>Dernières nouvelles</h4>
						<form class="footer-newslatter">
							<input type="email" placeholder="E-mail">
							<button class="site-btn">S'abonner</button>
							<p>Recevez les dernières nouvelles en vous abonnant!</p>
						</form>
					</div>
				</div>
			</div>
		</div>
		<div class="footer-bottom">
			<div class="footer-warp">
				<ul class="footer-menu">
					<li><a href="#">Terms & Conditions</a></li>
					<li><a href="#">Register</a></li>
					<li><a href="#">Privacy</a></li>
				</ul>
				<div class="">
	Copyright &copy; E-ducate <script>document.write(new Date().getFullYear());</script> All rights reserved.
</div>
			</div>
		</div>
	</footer>
	<!-- footer section end -->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'webuni/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'webuni/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webuni/js/mixitup.min.js' %}"></script>
	<script src="{% static 'webuni/js/circle-progress.min.js' %}"></script>
	<script src="{% static 'webuni/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'webuni/js/main.js' %}"></script>
	<script src="{% static 'webuni/js/freelancer.js' %}"></script>
	<script src="https://unpkg.com/aos@next/dist/aos.js"></script>
  <script>
    AOS.init();
  </script>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}


{% block content %}

<!-- Page info -->
<div class="page-info-section set-bg" data-setbg="{% static 'webuni/img/page-bg/4.jpg' %}">
  <div class="container">
    <div class="site-breadcrumb">
      <a href="#">Home</a>
      <span>Contact</span>
    </div>
  </div>
</div>
<!-- Page info end -->


<!-- search section -->
<section class="search-section ss-other-page">
  <div class="container">
    <div class="search-warp">
      <div class="section-title text-white">
        <h2><span>Rechercher votre cours</span></h2>
      </div>
      <div class="row">
        <div class="col-lg-10 offset-lg-1">
          <!-- search form -->
          <form class="course-search-form">
            <input type="text" placeholder="Course">
            <input type="text" class="last-m" placeholder="Category">
            <button class="site-btn btn-dark">Rechercher cours</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- search section end -->



<!-- Page -->
<section class="contact-page spad pb-0">
  <div class="container">
    <div class="row">
      <div class="col-lg-8">
        <div class="contact-form-warp">
          <div class="section-title text-white text-left">
            <h2>Entrer en contact:</h2>
            <p></p>
          </div>
          <form class="contact-form">
            <input type="text" placeholder="name">
            <input type="text" placeholder="E-mail">
            <input type="text" placeholder="Sujet">
            <textarea placeholder="Message"></textarea>
            <button class="site-btn">Envoyer Message</button>
          </form>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="contact-info-area">
          <div class="section-title text-left p-0">
            <h2>Contact Informations</h2>
            <p></p>
          </div>
          <div class="phone-number">
            <span>Ligne directe</span>
            <h2>+212 5-24-53-67-68</h2>
          </div>
          <ul class="contact-list">
            <li>Maroc<br></li>
            <li>+212609135685</li>
            <li>ounairzineb@gmail.com</li>
          </ul>
          <div class="social-links">
            <a href="#"><i class="fa fa-pinterest"></i></a>
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-dribbble"></i></a>
            <a href="#"><i class="fa fa-behance"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- Page end -->

{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<!-- Hero section -->
<section class="hero-section set-bg" data-setbg="{% static 'webuni/img/homeimage.jpg'%}">
  <div class="container">
    <div class="hero-text text-white">
      {% if request.user.is_authenticated %}
      <h2>Bonjour {% if request.user.profile.is_teacher == True %}
        professeur,
        {% endif %} {{ request.user.username|capfirst }}

       
      </h2>
      {% else %}
      <h2 style="color: #FF1493;">Les meilleurs cours en ligne gratuits!</h2>

      {% endif %}
      <p style="color: black; font-weight: bold;">E-ducate est une plate-forme en ligne pour l'enseignement de cours magistraux par une équipe dévouée d'enseignants et de formateurs expérimentés qui faciliteront l'apprentissage de manière simple grâce à des vidéos.</p>

    </div>
    <div class="row">
      <div class="col-lg-10 offset-lg-1">
        <form method="post" action="{% url 'courses:kerko_kurs' %}" class="intro-newslatter"> {% csrf_token %}
          <input name="search" type="text" placeholder="Rechercher votre cours">
          <button type="submit" class="site-btn">Rechercher cours</button>
        </form>
      </div>
    </div>
  </div>
</section>
<!-- Hero section end -->

<!-- categories section -->
<section class="categories-section spad">
  <div class="container">
    <div class="section-title">
      <h2 id="kurset">Catégories et Classes</h2>
      <p>Les leçons sont divisées en différentes catégories en fonction de leur classe et de leur niveau. Vous devez d'abord vous inscrire, puis assister à la classe correspondante.</p>
    </div>
    <div class="row">
      {% for cat in category %}
      <!-- categorie -->
      <div data-aos="zoom-in" class="col-lg-4 col-md-6">
        <div class="categorie-item">
          <div class="ci-thumb set-bg" data-setbg="{{ cat.imazhi.url }}"></div>
          <div class="ci-text">

            <h5>{{cat.titulli|capfirst}}</h5>

            <p>{{ cat.pershkrimi|capfirst }}</p>
            <span><a class="btn btn-success" href="/courses/{{ cat.id }}">Regardez les cas</a></span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
<!-- categories section end -->
{% if request.user.is_authenticated %}
{% else %}
<section class="course-section spad">
  <div class="container">
    <div class="section-title mb-0">
      <h2>Exemples de cours</h2>
      <p class="pb-3">Voici quelques exemples de cours que les étudiants suivent sur notre plateforme.</p>
    </div>
  </div>
  <div class="course-warp">                                     
    <div class="row course-items-area">
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 finance">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/p0fTc-CA4h0?controls=0"  frameborder="0" controls allowfullscreen></iframe>  
            
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Django Tutorial</h5>
              <p>Framework</p>
              <div class="students">Classe 1</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/44.jpg' %}"></div>
              <p>Mohamed AMEKSA, <span>Enseignant</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 design">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/GM6dQBmc-Xg?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Programmation</h5>
              <p>Algorithme</p>
              <div class="students">Classe 2</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Hassan ELBAHI, <span>Enseignant</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 web">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/45.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/V68VePj0F5A?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>Algèbre</h5>
              <p>Mathématique</p>
              <div class="students">Classe 3</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/46.jpg' %}"></div>
              <p>James TANTON, <span>Enseignant</span></p>
            </div>
          </div>
        </div>
      </div>
      <!-- course -->
      <div class="mix col-lg-3 col-md-4 col-sm-6 photo">
        <div class="course-item">
          <div class="course-thumb set-bg" data-setbg="{% static 'webuni/img/courses/4.jpg' %}">
            <iframe width="100%" height="290" src="https://www.youtube.com/embed/OKE3Q1avXg8?controls=0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </div>
          <div class="course-info">
            <div class="course-text">
              <h5>English</h5>
              <p>Vocabulary</p>
              <div class="students">Classe 4</div>
            </div>
            <div class="course-author">
              <div class="ca-pic set-bg" data-setbg="{% static 'webuni/img/authors/4.jpg' %}"></div>
              <p>Adam, <span>Enseignant</span></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endif %}
<!-- course section end -->

{% if request.user.is_authenticated %}

<!-- signup section -->
{% if request.user.profile.is_teacher == True %}
<div class="container">
  <h1 class="text-center">Votre compte a un accès enseignant</h1><br>
  <p class="text-center">En ayant un compte enseignant, vous avez désormais un accès plus complet à cette plateforme. Vous pouvez effectuer plus de fonctions que le compte étudiant initial. Certaines de ces fonctions sont :</p>

  <div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
    <div class="col-md-4 text-center">
      <h3 class="p-4">Vous pouvez créer votre propre classe</h3> 
      <a href="{% url 'courses:krijo_klase' %}" class="btn btn-outline-primary m-4">Créer la classe</a>
    </div>
    <div class="col-md-8">
      <img class="img-fluid w-100" src="{% static 'webuni/img/categories/4.jpg' %}" alt="">
    </div>
  </div>

  <div data-aos="fade-left" class="row mt-4 mb-4 bg-light">
      <div class="col-md-8">
        <img class="img-fluid w-100" src="{% static 'webuni/img/categories/2.jpg' %}" alt="">
      </div>
  
    <div class="col-md-4 text-center">
      <h3 class="p-4">Vous pouvez créer votre propre contenu</h3> 
      <a href="{% url 'courses:krijo_lende' %}" class="btn btn-outline-primary m-4">Créer le contenu</a>
  </div>
</div>

<div data-aos="fade-right" class="row mt-4 mb-4 bg-light">
  <div class="col-md-4 text-center">
    <h3 class="p-4">Vous pouvez télécharger vos propres leçons et vidéos.</h3> 
    <a href="{% url 'courses:krijo_mesim' %}" class="btn btn-outline-primary m-4">Créer la leçon</a>
  </div>
  <div class="col-md-8">
    <img class="img-fluid w-100" src="{% static 'webuni/img/categories/1.jpg' %}" alt="">
  </div>
</div>
</div>

{% else %}
<section data-aos="zoom-out" class="signup-section spad">
  <div class="signup-bg set-bg" data-setbg="{% static 'webuni/img/signup-bg.jpg' %}"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-6">
        <div class="signup-warp">
          <div class="section-title text-white text-left">
            <h2>Inscrivez-vous en tant qu'enseignant</h2>
            <p>Pour vous inscrire en tant qu'enseignant sur la plateforme, vous devez remplir les champs ci-dessous et vous aurez alors un accès complet pour télécharger des cours et des vidéos.</p>
            
          </div>
          <!-- signup form -->
          <form action="/kerkesa/" method="post" class="signup-form">{% csrf_token %}
            <input type="text" placeholder="name" name="name">
            <input type="text" placeholder="Email" name="e-mail">
            <input type="text" placeholder="numéro de téléphone" name="phone">
            <button class="site-btn">Envoyer la demande</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

{% endif %}
<!-- signup section end -->
{% else %}
{% endif %}

{% endblock content %}